Objectives:
After completing this lab you will be able to:
Load and use RandomUser API,using RandomUser() Python library
Load and use Fruityvice API,using requests python library
Load and use Open joke API ,using requests Python library

Get Methods:
get_cell()
get_city()
get_dob()
get_email()
get_first_name()
get_full_name()
get_gender()
get_id()
get_id_number()
get_id_type()
get_info()
get_last_name()
get_login_md5()
get_login_salt()
get_login_sha1()
get_login_sha256()
get_nat()
get_password()
get_phone()
get_picture()
get_postcode()
get_registered()
get_state()
get_street()
get_username()
get_zipcode()

In [ ]:
%pip install randomuser

In [ ]:
from randomuser import RandomUser
import pandas as pd

r=RandomUser()

#Then using generate_users() function, we get a list of random 10 users.

some_list=r.generate_users(10)
some_list

The "Get Methods" funcions mentioned ata the beginning of this otebook, can generate the  required parameters to construct a dataset.For example,to get full name,we call get_full_name() function.

In [3]:
name=r.get_full_name()
for user in some_list:
    print(user.get_full_name()," ",user.get_email())

Nieves Castro   nieves.castro@example.com
Irma Nogueira   irma.nogueira@example.com
Léon Da Silva   leon.dasilva@example.com
Katrina Reyes   katrina.reyes@example.com
تارا موسوی   tr.mwswy@example.com
David Pelletier   david.pelletier@example.com
Miro Caldeira   miro.caldeira@example.com
Melissa Wagner   melissa.wagner@example.com
Adolfo Medina   adolfo.medina@example.com
Nicole Ross   nicole.ross@example.com

In [ ]:
for user in some_list:
    print(user.get_picture())

To generate a table with information about the users, we can write a function containing all desirable parameters. For example, name,gender,city,etc.The parameters will depend on the requirements of the test to be performed .We call the Get Methods,Listed at the beginning of this notebook.Then, we return pandas dataframe with the users.

In [5]:
def get_users():
    users=[]
    for user in RandomUser.generate_users(20):
        users.append({"Name":user.get_full_name(),"Gender":user.get_gender(),"city":user.get_city(),"State":user.get_state(),"Email":user.get_email(),"DOB":user.get_dob(),"Picture":user.get_picture()})
    return pd.DataFrame(users)

In [6]:
get_users()

,Name,Gender,city,State,Email,DOB,Picture
0,Tako Orie,male,Readtsjerk,Groningen,tako.orie@example.com,1958-01-18T18:29:38.223Z,https://randomuser.me/api/portraits/men/84.jpg
1,Ljiljana Mathieu,female,Romont (Fr),Appenzell Innerrhoden,ljiljana.mathieu@example.com,1998-08-02T21:53:01.946Z,https://randomuser.me/api/portraits/women/37.jpg
2,Brennan Ferguson,male,Traralgon,Northern Territory,brennan.ferguson@example.com,1945-05-05T01:16:57.998Z,https://randomuser.me/api/portraits/men/30.jpg
3,Douglas Barnett,male,Warragul,Queensland,douglas.barnett@example.com,1951-10-03T20:36:15.421Z,https://randomuser.me/api/portraits/men/56.jpg
4,Sunniva Sigvartsen,female,Kylstad,Trøndelag,sunniva.sigvartsen@example.com,1961-02-15T00:12:04.750Z,https://randomuser.me/api/portraits/women/6.jpg
5,Melike Kahveci,female,Trabzon,Ordu,melike.kahveci@example.com,1966-05-13T02:30:39.334Z,https://randomuser.me/api/portraits/women/73.jpg
6,Alberto Gutierrez,male,Tyler,Colorado,alberto.gutierrez@example.com,1962-04-22T02:28:45.636Z,https://randomuser.me/api/portraits/men/92.jpg
7,Karla Nielsen,female,Branderup J,Danmark,karla.nielsen@example.com,1948-08-20T09:45:04.821Z,https://randomuser.me/api/portraits/women/26.jpg
8,Diana Mcdonalid,female,Bunbury,South Australia,diana.mcdonalid@example.com,1961-09-10T00:50:20.732Z,https://randomuser.me/api/portraits/women/77.jpg
9,Bettina Røgeberg,female,Ydstebøhamn,Troms - Romsa,bettina.rogeberg@example.com,1997-08-13T12:22:43.446Z,https://randomuser.me/api/portraits/women/31.jpg
10,Cecilie Møller,female,Sommersted,Hovedstaden,cecilie.moller@example.com,1976-02-02T22:00:15.063Z,https://randomuser.me/api/portraits/women/94.jpg
11,Johan Madsen,male,København V,Danmark,johan.madsen@example.com,1989-09-02T09:48:00.159Z,https://randomuser.me/api/portraits/men/47.jpg
12,Tomasz Paulissen,male,Delden,Utrecht,tomasz.paulissen@example.com,1979-02-04T14:39:25.384Z,https://randomuser.me/api/portraits/men/35.jpg
13,Myriam Fabre,female,Vals,Obwalden,myriam.fabre@example.com,1949-09-22T13:06:52.879Z,https://randomuser.me/api/portraits/women/45.jpg
14,Georgia Edwards,female,Wellington,Tasman,georgia.edwards@example.com,1974-09-12T12:02:02.161Z,https://randomuser.me/api/portraits/women/12.jpg
15,Marie Møller,female,Brondby,Danmark,marie.moller@example.com,1946-04-01T21:57:47.511Z,https://randomuser.me/api/portraits/women/62.jpg
16,Lea Walker,female,Cochrane,Nova Scotia,lea.walker@example.com,1998-09-18T10:14:50.613Z,https://randomuser.me/api/portraits/women/1.jpg
17,حامد رضایی,male,همدان,بوشهر,hmd.rdyy@example.com,1970-01-03T16:59:35.985Z,https://randomuser.me/api/portraits/men/49.jpg
18,Todd Boyd,male,Swords,Donegal,todd.boyd@example.com,1995-08-03T21:15:08.868Z,https://randomuser.me/api/portraits/men/81.jpg
19,Hazel Hall,female,Hamilton,Wellington,hazel.hall@example.com,1954-11-21T05:18:15.766Z,https://randomuser.me/api/portraits/women/45.jpg

In [ ]:
df1=pd.DataFrame(get_users())

Now we have pandas dataframe that can used for any testing purposes that the tester might have.

Example 2:Fruityvice API
Another more common way to use APIs , is through requests library. The next lab requests and HTTp, wil contain more information about request.

In [8]:
import requests
import json

We will obtain the fruityvice API data usint reqeusts.get("url") function. The data is in a json format

In [9]:
headers={
    "User-Agent":"Mozilla/5.0"
}
data = requests.get("https://web.archive.org/web/20240929211114/https://fruityvice.com/api/fruit/all",headers=headers)

In [11]:
results=json.loads(data.text)

In [ ]:
pd.DataFrame(results)

The result is in a nested json format. The 'nutrition'column contains multiple subcolumns,so the data needs to be flattened or normalized

In [13]:
df2=pd.json_normalize(results)
df2

,name,id,family,order,genus,nutritions.calories,nutritions.fat,nutritions.sugar,nutritions.carbohydrates,nutritions.protein
0,Persimmon,52,Ebenaceae,Rosales,Diospyros,81,0.00,18.00,18.00,0.00
1,Strawberry,3,Rosaceae,Rosales,Fragaria,29,0.40,5.40,5.50,0.80
2,Banana,1,Musaceae,Zingiberales,Musa,96,0.20,17.20,22.00,1.00
3,Tomato,5,Solanaceae,Solanales,Solanum,74,0.20,2.60,3.90,0.90
4,Pear,4,Rosaceae,Rosales,Pyrus,57,0.10,10.00,15.00,0.40
5,Durian,60,Malvaceae,Malvales,Durio,147,5.30,6.75,27.10,1.50
6,Blackberry,64,Rosaceae,Rosales,Rubus,40,0.40,4.50,9.00,1.30
7,Lingonberry,65,Ericaceae,Ericales,Vaccinium,50,0.34,5.74,11.30,0.75
8,Kiwi,66,Actinidiaceae,Struthioniformes,Apteryx,61,0.50,9.00,15.00,1.10
9,Lychee,67,Sapindaceae,Sapindales,Litchi,66,0.44,15.00,17.00,0.80
10,Pineapple,10,Bromeliaceae,Poales,Ananas,50,0.12,9.85,13.12,0.54
11,Fig,68,Moraceae,Rosales,Ficus,74,0.30,16.00,19.00,0.80
12,Gooseberry,69,Grossulariaceae,Saxifragales,Ribes,44,0.60,0.00,10.00,0.90
13,Passionfruit,70,Passifloraceae,Malpighiales,Passiflora,97,0.70,11.20,22.40,2.20
14,Plum,71,Rosaceae,Rosales,Prunus,46,0.28,9.92,11.40,0.70
15,Orange,2,Rutaceae,Sapindales,Citrus,43,0.20,8.20,8.30,1.00
16,GreenApple,72,Rosaceae,Rosales,Malus,21,0.10,6.40,3.10,0.40
17,Raspberry,23,Rosaceae,Rosales,Rubus,53,0.70,4.40,12.00,1.20
18,Watermelon,25,Cucurbitaceae,Cucurbitales,Citrullus,30,0.20,6.00,8.00,0.60
19,Lemon,26,Rutaceae,Sapindales,Citrus,29,0.30,2.50,9.00,1.10
20,Mango,27,Anacardiaceae,Sapindales,Mangifera,60,0.38,13.70,15.00,0.82
21,Blueberry,33,Rosaceae,Rosales,Fragaria,29,0.40,5.40,5.50,0.00
22,Apple,6,Rosaceae,Rosales,Malus,52,0.40,10.30,11.40,0.30
23,Guava,37,Myrtaceae,Myrtales,Psidium,68,1.00,9.00,14.00,2.60
24,Apricot,35,Rosaceae,Rosales,Prunus,15,0.10,3.20,3.90,0.50
25,Melon,41,Cucurbitaceae,Cucurbitaceae,Cucumis,34,0.00,8.00,8.00,0.00
26,Tangerine,77,Rutaceae,Sapindales,Citrus,45,0.40,9.10,8.30,0.00
27,Pitahaya,78,Cactaceae,Caryophyllales,Cactaceae,36,0.40,3.00,7.00,1.00
28,Lime,44,Rutaceae,Sapindales,Citrus,25,0.10,1.70,8.40,0.30
29,Pomegranate,79,Lythraceae,Myrtales,Punica,83,1.20,13.70,18.70,1.70
30,Dragonfruit,80,Cactaceae,Caryophyllales,Selenicereus,60,1.50,8.00,9.00,9.00
31,Grape,81,Vitaceae,Vitales,Vitis,69,0.16,16.00,18.10,0.72
32,Morus,82,Moraceae,Rosales,Morus,43,0.39,8.10,9.80,1.44
33,Feijoa,76,Myrtaceae,Myrtoideae,Sellowiana,44,0.40,3.00,8.00,0.60
34,Avocado,84,Lauraceae,Laurales,Persea,160,14.66,0.66,8.53,2.00
35,Kiwifruit,85,Actinidiaceae,Ericales,Actinidia,61,0.50,8.90,14.60,1.14
36,Cranberry,87,Ericaceae,Ericales,Vaccinium,46,0.10,4.00,12.20,0.40
37,Cherry,9,Rosaceae,Rosales,Prunus,50,0.30,8.00,12.00,1.00
38,Peach,86,Rosaceae,Rosales,Prunus,39,0.25,8.40,9.50,0.90
39,Jackfruit,94,Moraceae,Rosales,Artocarpus,95,0.00,19.10,23.20,1.72
40,Horned Melon,95,Cucurbitaceae,Cucurbitales,Cucumis,44,1.26,0.50,7.56,1.78
41,Hazelnut,96,Betulaceae,Fagales,Corylus,628,61.00,4.30,17.00,15.00
42,Pomelo,98,Rutaceae,Sapindales,Citrus,37,0.00,8.50,9.67,0.82
43,Mangosteen,99,Clusiaceae,Malpighiales,Garcinia,73,0.58,16.11,17.91,0.41
44,Pumpkin,100,Cucurbitaceae,Cucurbitales,Cucurbita,25,0.30,3.30,4.60,1.10
45,Japanese Persimmon,101,Ebenaceae,Ericales,Diospyros,70,0.20,13.00,19.00,0.60
46,Papaya,42,Caricaceae,Brassicales,Carica,39,0.30,4.40,5.80,0.50
47,Annona,103,Annonaceae,Rosales,Annonas,92,0.29,3.40,19.10,1.50
48,Ceylon Gooseberry,104,Salicaceae,Malpighiales,Dovyalis,47,0.30,8.10,9.60,1.20

Let's see if we can extract some information fromthsi dataframe. Perhaps, we need to know the family and genues of a cherry.

In [16]:
cherry=df2.loc[df2["name"]=="Cherry"]
(cherry.iloc[0]['family']),(cherry.iloc[0]['genus'])

('Rosaceae', 'Prunus')

Max nutritions

In [25]:
cols=['nutritions.calories','nutritions.fat',	'nutritions.sugar',	'nutritions.carbohydrates',	'nutritions.protein']

#Create sum column
df2['total']=df2[cols].sum(axis=1) #axis=1 means row wise sum

#Get row with maximum total
df3=df2.loc[df2['total'].idxmax()]#idxmax() finds the indes of the row with the maximu value
print(df3)

name                          Hazelnut
id                                  96
family                      Betulaceae
order                          Fagales
genus                          Corylus
nutritions.calories                628
nutritions.fat                    61.0
nutritions.sugar                   4.3
nutritions.carbohydrates          17.0
nutritions.protein                15.0
total                            725.3
Name: 41, dtype: object

https://mixedanalytics.com/blog/list-actually-free-open-no-auth-needed-apis/

This is list of free API