In [ ]:

import pandas as pd
import numpy as np

In [ ]:
df=pd.DataFrame(np.array([[1,2,3],[4,5,6],[7,8,9]]),columns=['a','b','c'])
df

In [5]:
df=df.transform(func=lambda x :x+10)
df

    a   b   c
0  11  12  13
1  14  15  16
2  17  18  19

In [6]:
result=df.transform(func=['sqrt'])
result

          a         b         c
       sqrt      sqrt      sqrt
0  3.316625  3.464102  3.605551
1  3.741657  3.872983  4.000000
2  4.123106  4.242641  4.358899

Writing JSON to a File:
This is usally called serialization. It is the process of coverting a object into special format
Which is suitable for transmitting over the network or storing in file or database
To handle the data flow in a file , the JSON libarary in Python uses the dump() or dumps() function to  convert the pyton objects into their respective JSON object. This makes it easy to write data to files

In [8]:
import json
person = {
    'first_name' : 'Mark',
    'last_name' : 'abc',
    'age' : 27,
    'address': {
        "streetAddress": "21 2nd Street",
        "city": "New York",
        "state": "NY",
        "postalCode": "10021-3100"
    }
}

Serialization using dump() function:
json.dump() method can be used for writing to JSON file.
Syntax: json.dump(dict,file_pointer)

Parameters:
1:dictionary--name of the dictionary which should be converted to JSON object.
2:file pointer--pointer of teh file opened in write or append mode

In [9]:
with open ('person.json','w') as f:
    json.dump(person,f)

Serialization using dumps() function
json.dumps() that helps in converting a dictionary to a JSON object.
It takes two parameters:
1:dictionary--name of the dictionary which should be converted to JSON object.
2:indent --defines the number of units for identation

In [ ]:
json_object=json.dumps(person,indent=4)

#Writing to sample.json
with open("sample.json","w") as outfile:
    outfile.write(json_object)
print(json_object)

Reading JSON to a File:
This process is usually called Deserialization - it is the reverse of serializzation. it converts the special format returned by the serialization back into a usable object.
Using json.load()
The JSON packaghe has json.load() function taht loads the json content from a json file into a dictionary.
It takes one parameter:
File pointer : A file pointer that points to a JSON file

In [11]:
import json
#opneing JSON file
with open('sample.json','r') as openfile:

    #Reading from json file
    json_object=json.load(openfile)

print(json_object)
print(type(json_object))

{'first_name': 'Mark', 'last_name': 'abc', 'age': 27, 'address': {'streetAddress': '21 2nd Street', 'city': 'New York', 'state': 'NY', 'postalCode': '10021-3100'}}
<class 'dict'>